"""Added NFC UID to User model

Revision ID: b80367c48fbf
Revises: 
Create Date: 2023-10-02 13:09:11.951943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80367c48fbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nfc_uid', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_nfc_uid', ['nfc_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_nfc_uid', type_='unique')
        batch_op.drop_column('nfc_uid')

    # ### end Alembic commands ###
