"""Add current SKU model

Revision ID: d47b2578f303
Revises: 14ac243eb593
Create Date: 2023-11-22 05:01:00.233304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47b2578f303'
down_revision = '14ac243eb593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_sku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('filament_inventory', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_filament_inventory_sku', ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filament_inventory', schema=None) as batch_op:
        batch_op.drop_constraint('uq_filament_inventory_sku', type_='unique')

    op.drop_table('current_sku')
    # ### end Alembic commands ###
